name: fiado
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.2
  path: ^1.9.0
  provider: ^6.1.1
  google_mobile_ads: ^4.0.0
  intl: ^0.19.0
  in_app_purchase: ^3.1.7
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  device_info_plus: ^10.0.1
  http: ^0.13.6
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.2
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/logo_fiado.png
    - assets/Logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_fiado.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#1B1E2F"
  image: assets/logo_fiado.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
