name = "fiadosync"
main = "src/index.js"
compatibility_date = "2024-05-20"

kv_namespaces = [
  { binding = "SYNC_DATA", id = "703029d0ea424998936e0c3bfff6174a" }
]

[[d1_databases]]
binding = "DB"
database_name = "fiados_d1"
database_id = "da06318f-e197-4d46-9c6e-1062d6652004"
